[project]
name = "aoc25"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "black>=25.11.0",
    "mypy>=1.19.0",
    "ruff>=0.14.7",
    "scipy>=1.16.3",
]
